pipeline:
  identifier: Build_grizmin_harnesscd_example_apps_1711958926683
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: test_build
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1711755563266
        repoName: grizmin/harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      echo "Exporting \$MY_HAR_ENV_OUT"
                      export MY_HAR_ENV_OUT=$(env | sort)
                      echo "\$MY_HAR_ENV_OUT equals to: ${MY_HAR_ENV_OUT}"
                    outputVariables:
                      - name: MY_HAR_ENV_OUT
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Output Shell Env
                  identifier: Output_Shell_Env
                  spec:
                    shell: Sh
                    command: "echo \"MY_HAR_ENV_OUT equal to: ${MY_HAR_ENV_OUT}\""
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
