pipeline:
  identifier: Build_grizmin_harnesscd_example_apps_1711755602824
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1711755563266
        repoName: grizmin/harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        command: echo hello world
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Python
                        command: print(f"Hello from Python!")
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
